import { FORMATION_TYPES } from './playerConstants';

export const POSITION_KEYS = {
  // Pairs formation
  LEFT_PAIR: 'leftPair',
  RIGHT_PAIR: 'rightPair', 
  SUB_PAIR: 'subPair',
  
  // Individual formations
  LEFT_DEFENDER: 'leftDefender',
  RIGHT_DEFENDER: 'rightDefender',
  LEFT_ATTACKER: 'leftAttacker', 
  RIGHT_ATTACKER: 'rightAttacker',
  SUBSTITUTE: 'substitute',
  
  // 7-player individual
  LEFT_DEFENDER_7: 'leftDefender7',
  RIGHT_DEFENDER_7: 'rightDefender7',  
  LEFT_ATTACKER_7: 'leftAttacker7',
  RIGHT_ATTACKER_7: 'rightAttacker7',
  SUBSTITUTE_7_1: 'substitute7_1',
  SUBSTITUTE_7_2: 'substitute7_2',
  
  // Common
  GOALIE: 'goalie'
};

export const FORMATION_POSITIONS = {
  [FORMATION_TYPES.PAIRS_7]: [POSITION_KEYS.LEFT_PAIR, POSITION_KEYS.RIGHT_PAIR, POSITION_KEYS.SUB_PAIR],
  [FORMATION_TYPES.INDIVIDUAL_6]: [POSITION_KEYS.LEFT_DEFENDER, POSITION_KEYS.RIGHT_DEFENDER, POSITION_KEYS.LEFT_ATTACKER, POSITION_KEYS.RIGHT_ATTACKER, POSITION_KEYS.SUBSTITUTE],
  [FORMATION_TYPES.INDIVIDUAL_7]: [POSITION_KEYS.LEFT_DEFENDER_7, POSITION_KEYS.RIGHT_DEFENDER_7, POSITION_KEYS.LEFT_ATTACKER_7, POSITION_KEYS.RIGHT_ATTACKER_7, POSITION_KEYS.SUBSTITUTE_7_1, POSITION_KEYS.SUBSTITUTE_7_2]
};

export const FORMATION_POSITIONS_WITH_GOALIE = {
  [FORMATION_TYPES.PAIRS_7]: [POSITION_KEYS.GOALIE, ...FORMATION_POSITIONS[FORMATION_TYPES.PAIRS_7]],
  [FORMATION_TYPES.INDIVIDUAL_6]: [POSITION_KEYS.GOALIE, ...FORMATION_POSITIONS[FORMATION_TYPES.INDIVIDUAL_6]],
  [FORMATION_TYPES.INDIVIDUAL_7]: [POSITION_KEYS.GOALIE, ...FORMATION_POSITIONS[FORMATION_TYPES.INDIVIDUAL_7]]
};