// Mock data for statistics components

export const mockTeamStats = {
  totalMatches: 15,
  goalsScored: 42,
  goalsConceded: 28,
  averageGoalsScored: 2.8,
  averageGoalsConceded: 1.9,
  wins: 9,
  draws: 3,
  losses: 3,
  winPercentage: 60,
  cleanSheets: 4,
  goalsPerMatchHome: 3.1,
  goalsPerMatchAway: 2.4
};

export const mockRecentMatches = [
  {
    id: 1,
    date: '2024-03-15',
    opponent: 'Hammarby IF',
    homeTeam: 'Djurgården',
    awayTeam: 'Hammarby IF',
    homeScore: 2,
    awayScore: 1,
    result: 'W',
    type: 'League'
  },
  {
    id: 2,
    date: '2024-03-10',
    opponent: 'AIK',
    homeTeam: 'AIK',
    awayTeam: 'Djurgården',
    homeScore: 1,
    awayScore: 1,
    result: 'D',
    type: 'League'
  },
  {
    id: 3,
    date: '2024-03-05',
    opponent: 'Malmö FF',
    homeTeam: 'Djurgården',
    awayTeam: 'Malmö FF',
    homeScore: 3,
    awayScore: 0,
    result: 'W',
    type: 'Cup'
  },
  {
    id: 4,
    date: '2024-02-28',
    opponent: 'Göteborg FC',
    homeTeam: 'Göteborg FC',
    awayTeam: 'Djurgården',
    homeScore: 0,
    awayScore: 2,
    result: 'W',
    type: 'League'
  },
  {
    id: 5,
    date: '2024-02-22',
    opponent: 'Elfsborg',
    homeTeam: 'Djurgården',
    awayTeam: 'Elfsborg',
    homeScore: 1,
    awayScore: 2,
    result: 'L',
    type: 'League'
  }
];

export const mockPlayerStats = [
  {
    id: 1,
    name: 'Erik Andersson',
    matchesPlayed: 15,
    goalsScored: 8,
    averageTimePerMatch: 28.5,
    percentageStartedAsSubstitute: 20,
    percentageTimeAsDefender: 60,
    percentageTimeAsMidfielder: 25,
    percentageTimeAsAttacker: 15,
    percentageTimeAsGoalkeeper: 0,
    matchesAsCaptain: 3,
    fairPlayAwards: 2
  },
  {
    id: 2,
    name: 'Lucas Svensson',
    matchesPlayed: 14,
    goalsScored: 12,
    averageTimePerMatch: 32.1,
    percentageStartedAsSubstitute: 14,
    percentageTimeAsDefender: 10,
    percentageTimeAsMidfielder: 30,
    percentageTimeAsAttacker: 60,
    percentageTimeAsGoalkeeper: 0,
    matchesAsCaptain: 5,
    fairPlayAwards: 1
  },
  {
    id: 3,
    name: 'Oliver Johansson',
    matchesPlayed: 15,
    goalsScored: 0,
    averageTimePerMatch: 35.0,
    percentageStartedAsSubstitute: 0,
    percentageTimeAsDefender: 0,
    percentageTimeAsMidfielder: 0,
    percentageTimeAsAttacker: 0,
    percentageTimeAsGoalkeeper: 100,
    matchesAsCaptain: 7,
    fairPlayAwards: 3
  },
  {
    id: 4,
    name: 'William Larsson',
    matchesPlayed: 13,
    goalsScored: 5,
    averageTimePerMatch: 25.8,
    percentageStartedAsSubstitute: 31,
    percentageTimeAsDefender: 70,
    percentageTimeAsMidfielder: 20,
    percentageTimeAsAttacker: 10,
    percentageTimeAsGoalkeeper: 0,
    matchesAsCaptain: 0,
    fairPlayAwards: 1
  },
  {
    id: 5,
    name: 'Hugo Karlsson',
    matchesPlayed: 12,
    goalsScored: 7,
    averageTimePerMatch: 29.2,
    percentageStartedAsSubstitute: 25,
    percentageTimeAsDefender: 15,
    percentageTimeAsMidfielder: 45,
    percentageTimeAsAttacker: 40,
    percentageTimeAsGoalkeeper: 0,
    matchesAsCaptain: 0,
    fairPlayAwards: 2
  },
  {
    id: 6,
    name: 'Liam Nilsson',
    matchesPlayed: 11,
    goalsScored: 3,
    averageTimePerMatch: 22.7,
    percentageStartedAsSubstitute: 45,
    percentageTimeAsDefender: 55,
    percentageTimeAsMidfielder: 35,
    percentageTimeAsAttacker: 10,
    percentageTimeAsGoalkeeper: 0,
    matchesAsCaptain: 0,
    fairPlayAwards: 1
  },
  {
    id: 7,
    name: 'Noah Eriksson',
    matchesPlayed: 10,
    goalsScored: 4,
    averageTimePerMatch: 18.5,
    percentageStartedAsSubstitute: 60,
    percentageTimeAsDefender: 20,
    percentageTimeAsMidfielder: 40,
    percentageTimeAsAttacker: 40,
    percentageTimeAsGoalkeeper: 0,
    matchesAsCaptain: 0,
    fairPlayAwards: 0
  }
];

export const mockMatchHistory = [
  {
    id: 1,
    date: '2024-03-15',
    opponent: 'Hammarby IF',
    homeTeam: 'Djurgården',
    awayTeam: 'Hammarby IF',
    homeScore: 2,
    awayScore: 1,
    type: 'League',
    format: '5v5',
    periods: 2,
    periodDuration: 20,
    formation: '2-2',
    location: 'Home'
  },
  {
    id: 2,
    date: '2024-03-10',
    opponent: 'AIK',
    homeTeam: 'AIK',
    awayTeam: 'Djurgården',
    homeScore: 1,
    awayScore: 1,
    type: 'League',
    format: '5v5',
    periods: 2,
    periodDuration: 20,
    formation: '2-2',
    location: 'Away'
  },
  {
    id: 3,
    date: '2024-03-05',
    opponent: 'Malmö FF',
    homeTeam: 'Djurgården',
    awayTeam: 'Malmö FF',
    homeScore: 3,
    awayScore: 0,
    type: 'Cup',
    format: '5v5',
    periods: 2,
    periodDuration: 25,
    formation: '1-2-1',
    location: 'Home'
  },
  {
    id: 4,
    date: '2024-02-28',
    opponent: 'Göteborg FC',
    homeTeam: 'Göteborg FC',
    awayTeam: 'Djurgården',
    homeScore: 0,
    awayScore: 2,
    type: 'League',
    format: '5v5',
    periods: 2,
    periodDuration: 20,
    formation: '2-2',
    location: 'Away'
  },
  {
    id: 5,
    date: '2024-02-22',
    opponent: 'Elfsborg',
    homeTeam: 'Djurgården',
    awayTeam: 'Elfsborg',
    homeScore: 1,
    awayScore: 2,
    type: 'League',
    format: '5v5',
    periods: 2,
    periodDuration: 20,
    formation: '2-2',
    location: 'Home'
  },
  {
    id: 6,
    date: '2024-02-15',
    opponent: 'Norrköping',
    homeTeam: 'Norrköping',
    awayTeam: 'Djurgården',
    homeScore: 1,
    awayScore: 3,
    type: 'Friendly',
    format: '5v5',
    periods: 2,
    periodDuration: 15,
    formation: '2-2',
    location: 'Away'
  },
  {
    id: 7,
    date: '2024-02-08',
    opponent: 'Helsingborg',
    homeTeam: 'Djurgården',
    awayTeam: 'Helsingborg',
    homeScore: 4,
    awayScore: 1,
    type: 'League',
    format: '5v5',
    periods: 2,
    periodDuration: 20,
    formation: '1-2-1',
    location: 'Home'
  },
  {
    id: 8,
    date: '2024-02-01',
    opponent: 'Sundsvall',
    homeTeam: 'Sundsvall',
    awayTeam: 'Djurgården',
    homeScore: 2,
    awayScore: 2,
    type: 'Cup',
    format: '5v5',
    periods: 2,
    periodDuration: 25,
    formation: '2-2',
    location: 'Away'
  }
];

export const mockMatchDetails = {
  1: {
    id: 1,
    date: '2024-03-15',
    opponent: 'Hammarby IF',
    homeTeam: 'Djurgården',
    awayTeam: 'Hammarby IF',
    homeScore: 2,
    awayScore: 1,
    type: 'League',
    format: '5v5',
    periods: 2,
    periodDuration: 20,
    formation: '2-2',
    location: 'Home',
    playerStats: [
      {
        id: 1,
        name: 'Erik Andersson',
        goalsScored: 1,
        totalTimePlayed: 35,
        timeAsDefender: 25,
        timeAsMidfielder: 10,
        timeAsAttacker: 0,
        timeAsGoalkeeper: 0,
        startingRole: 'defender',
        wasCaptain: true,
        receivedFairPlayAward: false
      },
      {
        id: 2,
        name: 'Lucas Svensson',
        goalsScored: 1,
        totalTimePlayed: 40,
        timeAsDefender: 0,
        timeAsMidfielder: 15,
        timeAsAttacker: 25,
        timeAsGoalkeeper: 0,
        startingRole: 'attacker',
        wasCaptain: false,
        receivedFairPlayAward: true
      },
      {
        id: 3,
        name: 'Oliver Johansson',
        goalsScored: 0,
        totalTimePlayed: 40,
        timeAsDefender: 0,
        timeAsMidfielder: 0,
        timeAsAttacker: 0,
        timeAsGoalkeeper: 40,
        startingRole: 'goalkeeper',
        wasCaptain: false,
        receivedFairPlayAward: false
      },
      {
        id: 4,
        name: 'William Larsson',
        goalsScored: 0,
        totalTimePlayed: 30,
        timeAsDefender: 20,
        timeAsMidfielder: 10,
        timeAsAttacker: 0,
        timeAsGoalkeeper: 0,
        startingRole: 'defender',
        wasCaptain: false,
        receivedFairPlayAward: false
      },
      {
        id: 5,
        name: 'Hugo Karlsson',
        goalsScored: 0,
        totalTimePlayed: 25,
        timeAsDefender: 0,
        timeAsMidfielder: 10,
        timeAsAttacker: 15,
        timeAsGoalkeeper: 0,
        startingRole: 'substitute',
        wasCaptain: false,
        receivedFairPlayAward: true
      },
      {
        id: 6,
        name: 'Liam Nilsson',
        goalsScored: 0,
        totalTimePlayed: 20,
        timeAsDefender: 15,
        timeAsMidfielder: 5,
        timeAsAttacker: 0,
        timeAsGoalkeeper: 0,
        startingRole: 'substitute',
        wasCaptain: false,
        receivedFairPlayAward: false
      }
    ]
  }
};