name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-test:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: 'npm'

      - name: Update npm to match local version
        run: npm install -g npm@11.4.1

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: CI=true npm test -- --verbose=false --silent --reporters=default

      - name: Debug Environment Variables and Whitespace
        run: |
          echo "REACT_APP_SUPABASE_URL is set: ${{ secrets.REACT_APP_SUPABASE_URL != '' }}"
          echo "REACT_APP_SUPABASE_ANON_KEY is set: ${{ secrets.REACT_APP_SUPABASE_ANON_KEY != '' }}"
          echo "=== ANON KEY WHITESPACE ANALYSIS ==="
          echo "Key length: $(echo -n '${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}' | wc -c)"
          echo "Key lines: $(echo '${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}' | wc -l)"
          echo "Contains newline: $(echo '${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}' | grep -c '\n' || echo '0')"
          echo "Contains space: $(echo '${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}' | grep -c ' ' || echo '0')"
          echo "Expected length: 211"
          echo "=== HEX DUMP (first 100 chars) ==="
          echo '${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}' | head -c 100 | xxd
          echo "=== HEX DUMP (last 100 chars) ==="
          echo '${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}' | tail -c 100 | xxd

      - name: Build
        run: CI=true && npm run build
        env:
          REACT_APP_SUPABASE_URL: ${{ secrets.REACT_APP_SUPABASE_URL }}
          REACT_APP_SUPABASE_ANON_KEY: ${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'

  deploy:
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4