name: Supabase DB Migration

on:
  push:
    branches:
      - main

jobs:
  migrate-db:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Force IPv4 resolution for Supabase host
        run: |
          DB_HOST="db.${{ secrets.SUPABASE_PROJECT_ID }}.supabase.co"
          IP_ADDR=$(getent ahosts "$DB_HOST" | grep -v '::' | awk '{ print $1 }' | head -n 1)
          echo "$IP_ADDR $DB_HOST" | sudo tee -a /etc/hosts

      - name: Check Supabase connection
        run: supabase db diff --use-migra --linked
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
