name: Supabase DB Migration

on:
  push:
    branches:
      - main

jobs:
  migrate-db:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Prioritize IPv4 for network connections
        run: echo "precedence ::ffff:0:0/96  100" | sudo tee -a /etc/gai.conf

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Check Supabase connection
        run: supabase db diff --use-migra --linked
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
